/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const IconCarbonAdd: typeof import('~icons/carbon/add.svelte')['default']
  const IconMdiChessPawn: typeof import('~icons/mdi/chess-pawn.svelte')['default']
  const IconSolarAddSquareBold: typeof import('~icons/solar/add-square-bold.svelte')['default']
  const IconSolarAddSquareLinear: typeof import('~icons/solar/add-square-linear.svelte')['default']
  const IconSolarCheckCircleBold: typeof import('~icons/solar/check-circle-bold.svelte')['default']
  const IconSolarCloseCircleBold: typeof import('~icons/solar/close-circle-bold.svelte')['default']
  const IconSolarDisketteBold: typeof import('~icons/solar/diskette-bold.svelte')['default']
  const IconSolarDownloadBold: typeof import('~icons/solar/download-bold.svelte')['default']
  const IconSolarDownloadSquareBold: typeof import('~icons/solar/download-square-bold.svelte')['default']
  const IconSolarGamepadBold: typeof import('~icons/solar/gamepad-bold.svelte')['default']
  const IconSolarMagniferLinear: typeof import('~icons/solar/magnifer-linear.svelte')['default']
  const IconSolarMagnifierLinear: typeof import('~icons/solar/magnifier-linear.svelte')['default']
  const IconSolarPenBold: typeof import('~icons/solar/pen-bold.svelte')['default']
  const IconSolarShareBold: typeof import('~icons/solar/share-bold.svelte')['default']
  const IconSolarShieldWarningBold: typeof import('~icons/solar/shield-warning-bold.svelte')['default']
  const IconSolarTrashBin: typeof import('~icons/solar/trash-bin.svelte')['default']
  const IconSolarTrashBin2Bold: typeof import('~icons/solar/trash-bin2-bold.svelte')['default']
  const IconSolarTrashBinBold: typeof import('~icons/solar/trash-bin-bold.svelte')['default']
  const IconSolarUploadBold: typeof import('~icons/solar/upload-bold.svelte')['default']
  const IconSolarUploadBoldDuotone: typeof import('~icons/solar/upload-bold-duotone.svelte')['default']
  const IconSolarUploadMinamalisticBold: typeof import('~icons/solar/upload-minamalistic-bold.svelte')['default']
  const IconSolarUploadMinimalisticBold: typeof import('~icons/solar/upload-minimalistic-bold.svelte')['default']
  const IconSolarUploadSquareBold: typeof import('~icons/solar/upload-square-bold.svelte')['default']
}
